---
kind: pipeline
type: docker
name: default

concurrency:
  limit: 1

steps:

- name: restore-cache-with-filesystem
  image: meltwater/drone-cache:latest
  pull: true
  settings:
    backend: "filesystem"
    restore: true
    cache_key: "volume"
    filesystem_cache_root: "/var/lib/drone/cache"
    mount:
      - 'dl'
  volumes:
  - name: cache
    path: /var/lib/drone/cache

- name: createimage
  image: docker:latest
  volumes:
  - name: docker_sock
    path: /var/run/docker.sock
  commands:
  - ls -l ./
  - ls -l /var/run/
  - docker build -t ecovec_buildroot .
  - chmod -R o+rw ./

- name: secrets
  image: ecovec_buildroot
  pull: if-not-exists
  environment:
    SSH_KEY:
      from_secret: tftp_ssh_key
  commands:
    - mkdir ./secrets/ && echo "$SSH_KEY" > ./secrets/tftp_ssh_key && chmod 0600 ./secrets/tftp_ssh_key

- name: bootstrap
  image: ecovec_buildroot
  pull: if-not-exists
  commands:
  - make bootstrap

- name: download
  image: ecovec_buildroot
  pull: if-not-exists
  commands:
  - make buildroot-dl

- name: rebuild-cache-with-filesystem
  image: meltwater/drone-cache:latest
  pull: true
  settings:
    backend: "filesystem"
    rebuild: true
    cache_key: "volume"
    filesystem_cache_root: "/var/lib/drone/cache"
    mount:
      - 'dl'
  volumes:
  - name: cache
    path: /var/lib/drone/cache

- name: dobuild
  image: ecovec_buildroot
  pull: if-not-exists
  commands:
  - make

- name: toolchain
  image: ecovec_buildroot
  pull: if-not-exists
  commands:
  - make buildroot-toolchain

- name: publish
  image: plugins/github-release
  settings:
    api_key:
      from_secret: deploy_key
    files:
      - outputs/*
    checksum:
      - sha256
      - sha512
  when:
    event: tag

volumes:
  - name: cache
    host: 
      path: /tmp/ecovec_buildroot_cache
  - name: docker_sock
    host:
      path: /var/run/docker.sock

...
